kind: Pod
apiVersion: v1
metadata:
  name: nginx-my-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-my-pod2
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
