apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: webserver
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: httpd-pod
  labels:
    app: webserver
spec:
  containers:
    - name: httpd-container
      image: httpd
      ports:
        - containerPort: 80

