apiVersion: v1
kind: Pod
metadata:
  name: nginx-blue
  labels:
    app: webserver
spec:
  containers:
    - name: nginx-bluecontainer
      image: princebansal7/nginx-custom:blue-v4
      ports:
        - containerPort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-green
  labels:
    app: webserver
spec:
  containers:
    - name: nginx-green-container
      image: princebansal7/nginx-custom:green-v2
      ports:
        - containerPort: 80

