apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-creator
  namespace: rbac-demo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator-role
  namespace: rbac-demo
rules:
  - apiGroups: [""] # core API group (v1)
    resources: ["pods"]
    verbs: ["create", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-binding
  namespace: rbac-demo
subjects:
  - kind: ServiceAccount
    name: pod-creator
    namespace: rbac-demo
roleRef:
  kind: Role
  name: pod-creator-role
  apiGroup: rbac.authorization.k8s.io