apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-label
  template:
    metadata:
      labels:
        app: backend-label
    spec:
      containers:
        - name: be-container
          image: princebansal7/node-be-env:secrets-v2
          ports:
            - containerPort: 3008
          ############# env vars from configmap #################
          env:
            - name: DB_URL # final env variable
              valueFrom:
                configMapKeyRef:
                  name: env-configmap # should be same as configmap resource
                  key: db_url # data key mentioned in configMap
            - name: PORT # final env variable
              valueFrom:
                configMapKeyRef:
                  name: env-configmap # should be same as configmap resource
                  key: port # data key mentioned in configMap
            ############# env vars from secrets #################
            - name: USERNAME # final env variable
              valueFrom:
                secretKeyRef:
                  name: env-secrets # should be same as secret resource
                  key: username # data key mentioned in secret
            - name: PASSWORD # final env variable
              valueFrom:
                secretKeyRef:
                  name: env-secrets # should be same as secret resource
                  key: password # data key mentioned in secret
