apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-label
  template:
    metadata:
      labels:
        app: db-label
    spec:
      containers:
        - name: db-container
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: pass123 # same will be in db connection string
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db-cip-service # same will be in db connection string
spec:
  selector:
    app: db-label
  ports:
    - protocol: TCP
      port: 5432 # service port (same will be db connection string)
      targetPort: 5432
  type: ClusterIP
