apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  db_url: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzMTIzQGRiLWNpcC1zZXJ2aWNlLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi9wb3N0Z3Jlcwo= # db url encoded

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: princebansal7/node-db-mimic-ingress:v2
          ports:
            - containerPort: 3000
          env:
            - name: DB_URL # final env variable
              valueFrom:
                secretKeyRef:
                  name: db-secret # should be same as secret resource
                  key: db_url # data key mentioned in secret

---
apiVersion: v1
kind: Service
metadata:
  name: backend-cip-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000 # service's PORT, which redirects to target port (POD's PORT)
      targetPort: 3000 # POD's PORT
  type: ClusterIP # as we want to connect it with db pods internally
