apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: httpd
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-cip-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # service's PORT, which redirects to target port (POD's PORT)
      targetPort: 80 # POD's PORT
  type: ClusterIP # as we want to connect it with db pods internally
